// Builds src/data/map.js from a Natural Earth GeoJSON (public domain), with no runtime dependency.
// Usage: node scripts/build-map.mjs <ne_50m_admin_0_countries.geojson>
// Source: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_50m_admin_0_countries.geojson
// The 50m scale is needed: the 110m file has no Monaco and no Andorra.
import { readFileSync, writeFileSync } from 'node:fs'

const input = process.argv[2]
if (!input) throw new Error('Usage: node scripts/build-map.mjs <countries.geojson>')

// Europe and the Mediterranean: from Morocco to western Russia.
const BOX = { west: -12, east: 46, south: 27, north: 63 }
const UNITS_PER_DEGREE = 10
const MIN_STEP = 0.4 // in map units
// Shrink longitudes by cos(45°) so mid-latitude Europe keeps its usual shape.
const LON_SCALE = Math.cos((45 * Math.PI) / 180)

const project = ([lon, lat]) => [
  Math.round((lon - BOX.west) * LON_SCALE * UNITS_PER_DEGREE * 10) / 10,
  Math.round((BOX.north - lat) * UNITS_PER_DEGREE * 10) / 10,
]

// Sutherland–Hodgman: clip one ring against the box, edge by edge.
function clip(ring) {
  const edges = [
    { inside: (p) => p[0] >= BOX.west, cut: (a, b) => cutAt(a, b, 0, BOX.west) },
    { inside: (p) => p[0] <= BOX.east, cut: (a, b) => cutAt(a, b, 0, BOX.east) },
    { inside: (p) => p[1] >= BOX.south, cut: (a, b) => cutAt(a, b, 1, BOX.south) },
    { inside: (p) => p[1] <= BOX.north, cut: (a, b) => cutAt(a, b, 1, BOX.north) },
  ]
  let out = ring
  for (const edge of edges) {
    const pts = out
    out = []
    for (let i = 0; i < pts.length; i++) {
      const cur = pts[i]
      const prev = pts[(i + pts.length - 1) % pts.length]
      if (edge.inside(cur)) {
        if (!edge.inside(prev)) out.push(edge.cut(prev, cur))
        out.push(cur)
      } else if (edge.inside(prev)) {
        out.push(edge.cut(prev, cur))
      }
    }
    if (!out.length) return out
  }
  return out
}

function cutAt(a, b, axis, value) {
  const t = (value - a[axis]) / (b[axis] - a[axis])
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t]
}

function ringPath(ring) {
  const pts = []
  for (const p of clip(ring).map(project)) {
    const last = pts[pts.length - 1]
    // Drop points closer than MIN_STEP to the previous one: invisible at this size, about a sixth off the file.
    if (!last || Math.hypot(last[0] - p[0], last[1] - p[1]) >= MIN_STEP) pts.push(p)
  }
  if (pts.length < 3) return ''
  return `M${pts.map((p) => p.join(' ')).join('L')}Z`
}

const geo = JSON.parse(readFileSync(input, 'utf8'))
const countries = []
for (const f of geo.features) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates
  const d = polys.flatMap((poly) => poly.map(ringPath)).join('')
  if (!d) continue
  const p = f.properties
  countries.push({ id: p.ADM0_A3, name: p.NAME, d, label: project([p.LABEL_X, p.LABEL_Y]) })
}

const width = Math.round((BOX.east - BOX.west) * LON_SCALE * UNITS_PER_DEGREE)
const height = (BOX.north - BOX.south) * UNITS_PER_DEGREE
const file = `// Generated by scripts/build-map.mjs from Natural Earth 1:50m countries (public domain). Do not edit by hand.
export const MAP = ${JSON.stringify({ width, height, countries })}
`
writeFileSync(new URL('../src/data/map.js', import.meta.url), file)
console.log(`map.js: ${countries.length} countries, ${width}x${height}, ${(file.length / 1024).toFixed(0)} KB`)
